title: Default Page
preset: page
icon: text

fields:
  hed:
    type: text
    label: Header
    default: "{{ page.title }}"
    max: 36
  dek:
    type: text
    label: Subtitle
    max: 72
  text:
    label: Content
    type: textarea
    size: large
    buttons:
      - headlines
      - bold
      - italic
      - link
      - email
      - file
      - code
      - ul
      - ol
  tags:
    label: Tags
    type: tags
    options: query
    query: site.index.pluck("tags", ",", true)
    required: true
  date:
    label: Planted
    type: date
    display: dd MMM YYYY
    width: 1/3
    default: today
    required: true
  tended:
    label: Tended
    type: date
    display: dd MMM YYYY
    width: 1/3
  time:
    label: Time
    type: time
    default: now
    notation: 24
    step:
      unit: minute
      size: 1
    width: 1/3
  addressLocality:
    label: City
    type: text
    width: 1/3
    default: "Raleigh"
  addressRegion:
    label: State or Region
    type: text
    width: 1/3
    default: "NC"
  addressCountry:
    label: Country
    type: text
    width: 1/3
    default: "US"

sidebar:
    pages:
      type: pages
      template: default
    files:
      type: files
    images:
      label: Images
      type: files
      multiple: true
      layout: cards
      template: blocks/image
