# site/blueprints/site.yml
title: Site
tabs:
  pages:
    label: pages
    icon: page
    columns:
      - width: 2/3
        sections:
          published:
            type: pages

      - width: 1/3
        sections:
          personal:
            type: fields
            fields:
              journal:
                label: Journal
                icon: text
                link: /panel/pages/journal
              notes:
                label: Notes
                icon: sticky-note
                link: /panel/pages/notes
              links:
                label: Links
                icon: link
                link: /panel/pages/links

  general:
    label: Settings
    icon: settings
    columns:
      - width: 1/2
        sections:
          settings:
            type: fields
            fields:
              site_title:
                label: Site Title
                type: text
              site_description:
                label: Site Description
                type: textarea
              default_location:
                label: Default Location
                type: text

  header:
    label: Navigation
    icon: title
    columns:
      - width: 1/3
        sections:
          primary_navigation:
            type: pages
            headline: Primary Navigation
            template: default
            status: published
            sortable: true
      - width: 1/3
        sections:
          secondary_navigation:
            type: pages
            headline: Secondary Navigation
            template: default
            status: published
            sortable: true
      - width: 1/3
        sections:
          tertiary_navigation:
            type: pages
            headline: Tertiary Navigation
            template: default
            status: published
            sortable: true

  footer:
    label: Footer
    icon: download
    columns:
      - width: 1/3
          fields:
            footer_nav:
              label: Footer Nav
              type: structure
              fields:
                linkTitle:
                  type: text
                  label: Menu item title
                link:
                  type: link
                  label: Link
                  options:
                    - page
                    - url
      - width: 1/3
        sections:
          footer_col2:
            type: fields
            fields:
              footer_col2_title:
                label: About Me
                type: text
              footer_col2_pages:
                label: About me
                type: pages
                multiple: true
                status: published

      - width: 1/3
          fields:
            footer_social:
              label: Social Navigation
              type: structure
              fields:
                platform:
                  label: Platform
                  type: text
                url:
                  label: URL
                  type: url
                logo:
                  label: Logo
                  type: files
                  multiple: false
